name: devcontainer_environment
channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - pip==22.3.1
  - python==3.9.16
  - pip:
      # code-check
      - black==22.3.0
      - isort==5.10.1
      - flake8==6.0.0
      - flake8-comprehensions==3.10.1
      - flake8-bugbear==21.4.3
      - flake8-builtins==1.5.3
      - flake8-absolute-import==1.0
      - bandit==1.7.4
      - flake8-bandit==4.1.1
      #
      - sqlalchemy~=1.4.0
      - torch~=1.13.1
      - torchvision==0.14.1
      - matplotlib~=3.6.0
      - ipykernel
      - pytest
      - pytest-cov
      - pydantic~=1.10
      - opencv-python-headless~=4.6.0.66
      - pandas~=1.5.3
